# -*- coding:utf-8 -*-
# by pandonglin

STATE_TYPE_START = 1  # 开始
STATE_TYPE_END = 2    # 结束

TICKET_ACT_STATE_DRAFT = 0    # 初始化
TICKET_ACT_STATE_DOING = 1  # 进行中
TICKET_ACT_STATE_PASS = 2     # 已通过
TICKET_ACT_STATE_REFUSE = 3   # 已拒绝
TICKET_ACT_STATE_FINISH = 4   # 已完成
TICKET_ACT_STATE_FAIL = 5     # 已失败
TICKET_ACT_STATE_CLOSE = 6   # 已关闭
TICKET_ACT_STATE_STOP = 7     # 已中止

TICKET_ACT_STATE_END = [TICKET_ACT_STATE_REFUSE, TICKET_ACT_STATE_FINISH, TICKET_ACT_STATE_CLOSE, TICKET_ACT_STATE_STOP]

TICKET_ACT_STATE_MAP = (
    (TICKET_ACT_STATE_DRAFT, "初始化"),
    (TICKET_ACT_STATE_DOING, "进行中"),
    (TICKET_ACT_STATE_PASS, "已通过"),
    (TICKET_ACT_STATE_REFUSE, "已拒绝"),
    (TICKET_ACT_STATE_FINISH, "已完成"),
    (TICKET_ACT_STATE_FAIL, "已失败"),
    (TICKET_ACT_STATE_CLOSE, "已关闭"),
    (TICKET_ACT_STATE_STOP, "已中止"),
)


PARTICIPANT_TYPE_PERSONAL = 1  # 个人
PARTICIPANT_TYPE_MULTI = 2     # 多人
PARTICIPANT_TYPE_DEPT = 3      # 部门
PARTICIPANT_TYPE_ROLE = 4      # 角色
PARTICIPANT_TYPE_ONCALL = 5    # oncall
PARTICIPANT_TYPE_ROBOT = 6     # 机器人，脚本
PARTICIPANT_TYPE_FIELD = 7     # 工单字段(用户名类型的)
PARTICIPANT_TYPE_HOOK = 8      # hook方式

PARTICIPANT_TYPE = (
    (PARTICIPANT_TYPE_PERSONAL, "个人"),
    (PARTICIPANT_TYPE_MULTI, "多人"),
    (PARTICIPANT_TYPE_DEPT, "部门"),
    (PARTICIPANT_TYPE_ROLE, "角色"),
    (PARTICIPANT_TYPE_ONCALL, "oncall"),
    (PARTICIPANT_TYPE_ROBOT, "机器人"),
    (PARTICIPANT_TYPE_FIELD, "工单的字段"),
    (PARTICIPANT_TYPE_HOOK, "hook"),  # 第3方
)

TRANSITION_TYPE_COMMON = 1  # 常规流转
TRANSITION_TYPE_TIMER = 2   # 其他

TRANSITION_ATTRIBUTE_TYPE_ACCEPT = 1  # 同意
TRANSITION_ATTRIBUTE_TYPE_REFUSE = 2  # 拒绝
TRANSITION_ATTRIBUTE_TYPE_TIMEOUT = 3   # 超时
TRANSITION_ATTRIBUTE_TYPE_OTHER = 4   # 其他

TRANSITION_INTERVENE_TYPE_DELIVER = 1  # 转交操作
TRANSITION_INTERVENE_TYPE_ADD_NODE = 2  # 加签操作
TRANSITION_INTERVENE_TYPE_ADD_NODE_END = 3  # 加签处理完成
TRANSITION_INTERVENE_TYPE_ACCEPT = 4  # 接单操作
TRANSITION_INTERVENE_TYPE_COMMENT = 5  # 评论操作
TRANSITION_INTERVENE_TYPE_DELETE = 6  # 删除操作
TRANSITION_INTERVENE_TYPE_CLOSE = 7   # 强制关闭操作
TRANSITION_INTERVENE_TYPE_ALTER_STATE = 8  # 强制修改状态操作
TRANSITION_INTERVENE_TYPE_HOOK = 9  # hook操作
TRANSITION_INTERVENE_TYPE_RETREAT = 10  # 撤回

FIELD_ATTRIBUTE_RO = 1  # 只读
FIELD_ATTRIBUTE_REQUIRED = 2  # 必填
FIELD_ATTRIBUTE_OPTIONAL = 3  # 可选

TICKET_PERMISSION_HANDLE = 1  # 处理权限
TICKET_PERMISSION_VIEW = 2    # 查看权限

TICKET_BASE_FIELD_LIST = ['id', 'sn', 'title', 'state_id', 'parent_ticket_id', 'parent_ticket_state_id',
                               'participant_type_id', 'participant', 'workflow_id', 'ticket_type_id',
                               'creator', 'is_deleted', 'gmt_created', 'gmt_modified', 'script_run_last_result']
